[package]
name = "wallpaper-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
rand = "0.8.5"

[profile.release]
lto = "fat"
strip = true
codegen-units = 1

[lints.clippy]
pedantic = "warn"
